### ISSUE TITLE
Text contrast is wrong

### ISSUE THREAD

**Issue by ImMattDavison** [Rutuj-Runwal/RRAdblocker#11]
![image](https://user-images.githubusercontent.com/80921257/195831476-6be24a7c-076f-429c-949d-b4e0dae05b70.png)

**Comment by Aamir-Ansari-almost** [comment]
I would like to work on this issue

**Comment by Rutuj-Runwal** [comment]
> I would like to work on this issue

Thank you for your interest but a pr has already been made

**Comment by ImMattDavison** [comment]
Sorry I already amended this
