### ISSUE TITLE
Fix bug : mobile responsiveness skewed 

### ISSUE THREAD

**Issue by Zeuhz-Droid** [Rutuj-Runwal/RRAdblocker#17]
I noticed your site is having a responsiveness issue and was hoping I could take on this, under #hacktoberfest.
![Screenshot (39)](https://user-images.githubusercontent.com/76104838/195913299-a6727694-5869-4fc9-83c3-74d3d96559ae.png)

**Comment by Rutuj-Runwal** [comment]
Sure

**Comment by Zeuhz-Droid** [comment]
Is it possible you tag/label this issue hacktoberfest?
