### ISSUE TITLE
make website look good on mobile

### ISSUE THREAD

**Issue by Davethadev** [Rutuj-Runwal/RRAdblocker#2]
Hey there. The website doesn't look too good on smaller screens. I'd like to contribute under hacktoberfest to making the website responsive for mobile and tablet devices.

**Comment by Rutuj-Runwal** [comment]
Sure go ahead

**Comment by Davethadev** [comment]
Alright would get started on it. Thanks

**Comment by Abhishek8287** [comment]
Where is the website link

**Comment by Rutuj-Runwal** [comment]
> Where is the website link
> 

https://rutuj-runwal.github.io/RRAdblocker/

**Comment by Davethadev** [comment]
@Rutuj-Runwal I already made a pull request that solves this issue. Please kindly check it out

**Comment by Rutuj-Runwal** [comment]
> @Rutuj-Runwal I already made a pull request that solves this issue. Please kindly check it out

Yes taking a look now, didn't had the time to test it earlier.

**Comment by Davethadev** [comment]
Oh alright. I see you've merged my pr after checking it out. Thanks
